use std::path::PathBuf;

use crate::discovery::{
    DiscoveryContext, KnownPath,
    linux::{opencode_user_config, opencode_user_data_root},
    windows::{claude_user_settings, codex_user_config},
};

pub fn discover_known_roots(context: &DiscoveryContext) -> Vec<KnownPath> {
    let native_environment = infer_environment(&context.home_dir);
    let mut roots = vec![
        KnownPath::new(
            "codex",
            "config",
            native_environment,
            codex_user_config(&context.home_dir),
        ),
        KnownPath::new(
            "claude-code",
            "config",
            native_environment,
            claude_user_settings(&context.home_dir),
        ),
        KnownPath::new(
            "opencode",
            "config",
            native_environment,
            opencode_user_config(&context.home_dir, context.xdg_config_home.as_deref()),
        ),
        KnownPath::new(
            "gemini-cli",
            "config",
            native_environment,
            context.home_dir.join(".gemini").join("settings.json"),
        ),
        KnownPath::new(
            "github-copilot-cli",
            "config",
            native_environment,
            context.home_dir.join(".copilot").join("config.json"),
        ),
        KnownPath::new(
            "qwen-cli",
            "config",
            native_environment,
            context.home_dir.join(".qwen").join("settings.json"),
        ),
        KnownPath::new(
            "factory-droid",
            "config",
            native_environment,
            context.home_dir.join(".factory").join("settings.json"),
        ),
        KnownPath::new(
            "openclaw",
            "config",
            native_environment,
            context.home_dir.join(".openclaw").join("openclaw.json"),
        ),
    ];

    if let Some(wsl_home) = &context.wsl_home_dir {
        roots.push(KnownPath::new(
            "codex",
            "config",
            "wsl",
            PathBuf::from(wsl_home).join(".codex").join("config.toml"),
        ));
        roots.push(KnownPath::new(
            "claude-code",
            "config",
            "wsl",
            PathBuf::from(wsl_home)
                .join(".claude")
                .join("settings.json"),
        ));
        roots.push(KnownPath::new(
            "opencode",
            "config",
            "wsl",
            opencode_user_config(wsl_home, None),
        ));
        roots.push(KnownPath::new(
            "gemini-cli",
            "config",
            "wsl",
            PathBuf::from(wsl_home)
                .join(".gemini")
                .join("settings.json"),
        ));
        roots.push(KnownPath::new(
            "github-copilot-cli",
            "config",
            "wsl",
            PathBuf::from(wsl_home).join(".copilot").join("config.json"),
        ));
        roots.push(KnownPath::new(
            "qwen-cli",
            "config",
            "wsl",
            PathBuf::from(wsl_home).join(".qwen").join("settings.json"),
        ));
        roots.push(KnownPath::new(
            "factory-droid",
            "config",
            "wsl",
            PathBuf::from(wsl_home)
                .join(".factory")
                .join("settings.json"),
        ));
        roots.push(KnownPath::new(
            "openclaw",
            "config",
            "wsl",
            PathBuf::from(wsl_home)
                .join(".openclaw")
                .join("openclaw.json"),
        ));
    }

    roots
}

pub fn discover_known_session_roots(context: &DiscoveryContext) -> Vec<KnownPath> {
    let native_environment = infer_environment(&context.home_dir);
    let mut roots = vec![
        KnownPath::new(
            "codex",
            "session",
            native_environment,
            context.home_dir.join(".codex").join("sessions"),
        ),
        KnownPath::new(
            "claude-code",
            "session",
            native_environment,
            context.home_dir.join(".claude").join("projects"),
        ),
        KnownPath::new(
            "opencode",
            "session",
            native_environment,
            opencode_user_data_root(&context.home_dir, context.xdg_data_home.as_deref()),
        ),
        KnownPath::new(
            "gemini-cli",
            "session",
            native_environment,
            context.home_dir.join(".gemini").join("tmp"),
        ),
        KnownPath::new(
            "github-copilot-cli",
            "session",
            native_environment,
            context.home_dir.join(".copilot").join("session-state"),
        ),
        KnownPath::new(
            "qwen-cli",
            "session",
            native_environment,
            context.home_dir.join(".qwen").join("projects"),
        ),
        KnownPath::new(
            "roo-code",
            "session",
            native_environment,
            context
                .home_dir
                .join(".config")
                .join("Code")
                .join("User")
                .join("globalStorage")
                .join("rooveterinaryinc.roo-cline")
                .join("tasks"),
        ),
        KnownPath::new(
            "factory-droid",
            "session",
            native_environment,
            context.home_dir.join(".factory"),
        ),
        KnownPath::new(
            "openclaw",
            "session",
            native_environment,
            context.home_dir.join(".openclaw"),
        ),
        KnownPath::new(
            "openclaw",
            "session",
            native_environment,
            context.home_dir.join(".clawdbot"),
        ),
        KnownPath::new(
            "openclaw",
            "session",
            native_environment,
            context.home_dir.join(".moltbot"),
        ),
        KnownPath::new(
            "openclaw",
            "session",
            native_environment,
            context.home_dir.join(".moldbot"),
        ),
    ];

    if let Some(wsl_home) = &context.wsl_home_dir {
        roots.push(KnownPath::new(
            "codex",
            "session",
            "wsl",
            PathBuf::from(wsl_home).join(".codex").join("sessions"),
        ));
        roots.push(KnownPath::new(
            "claude-code",
            "session",
            "wsl",
            PathBuf::from(wsl_home).join(".claude").join("projects"),
        ));
        roots.push(KnownPath::new(
            "opencode",
            "session",
            "wsl",
            opencode_user_data_root(wsl_home, None),
        ));
        roots.push(KnownPath::new(
            "gemini-cli",
            "session",
            "wsl",
            PathBuf::from(wsl_home).join(".gemini").join("tmp"),
        ));
        roots.push(KnownPath::new(
            "github-copilot-cli",
            "session",
            "wsl",
            PathBuf::from(wsl_home)
                .join(".copilot")
                .join("session-state"),
        ));
        roots.push(KnownPath::new(
            "qwen-cli",
            "session",
            "wsl",
            PathBuf::from(wsl_home).join(".qwen").join("projects"),
        ));
        roots.push(KnownPath::new(
            "roo-code",
            "session",
            "wsl",
            PathBuf::from(wsl_home)
                .join(".config")
                .join("Code")
                .join("User")
                .join("globalStorage")
                .join("rooveterinaryinc.roo-cline")
                .join("tasks"),
        ));
        roots.push(KnownPath::new(
            "roo-code",
            "session",
            "wsl",
            PathBuf::from(wsl_home)
                .join(".vscode-server")
                .join("data")
                .join("User")
                .join("globalStorage")
                .join("rooveterinaryinc.roo-cline")
                .join("tasks"),
        ));
        roots.push(KnownPath::new(
            "factory-droid",
            "session",
            "wsl",
            PathBuf::from(wsl_home).join(".factory"),
        ));
        roots.push(KnownPath::new(
            "openclaw",
            "session",
            "wsl",
            PathBuf::from(wsl_home).join(".openclaw"),
        ));
        roots.push(KnownPath::new(
            "openclaw",
            "session",
            "wsl",
            PathBuf::from(wsl_home).join(".clawdbot"),
        ));
        roots.push(KnownPath::new(
            "openclaw",
            "session",
            "wsl",
            PathBuf::from(wsl_home).join(".moltbot"),
        ));
        roots.push(KnownPath::new(
            "openclaw",
            "session",
            "wsl",
            PathBuf::from(wsl_home).join(".moldbot"),
        ));
    }

    roots
}

fn infer_environment(home_dir: &std::path::Path) -> &'static str {
    if home_dir
        .to_string_lossy()
        .chars()
        .nth(1)
        .is_some_and(|character| character == ':')
    {
        "windows"
    } else {
        "linux"
    }
}
